{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.sfsakhawat999",
    "module": "mpvRex-libmpv",
    "version": "v0.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mpvRex-libmpv-v0.0.3.aar",
          "url": "mpvRex-libmpv-v0.0.3.aar",
          "size": 80134755,
          "sha512": "32362cc16540d51a0172382e2d1fde103979290e3913a2cace68ff611150cf93e5d13f20106b43f02dabb3e0dd86a74c3cc8e3e188794b068c2948dafe87579c",
          "sha256": "b5591f28156ed53f3eab71d0e302846a50a2c3fe997b4622a9c6113a0862b442",
          "sha1": "0af7f1aca0997b546d4c6fcfcd4a4ce3c710db4e",
          "md5": "01f2baf3b7dc7129d809d25130aea217"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        }
      ],
      "files": [
        {
          "name": "mpvRex-libmpv-v0.0.3.aar",
          "url": "mpvRex-libmpv-v0.0.3.aar",
          "size": 80134755,
          "sha512": "32362cc16540d51a0172382e2d1fde103979290e3913a2cace68ff611150cf93e5d13f20106b43f02dabb3e0dd86a74c3cc8e3e188794b068c2948dafe87579c",
          "sha256": "b5591f28156ed53f3eab71d0e302846a50a2c3fe997b4622a9c6113a0862b442",
          "sha1": "0af7f1aca0997b546d4c6fcfcd4a4ce3c710db4e",
          "md5": "01f2baf3b7dc7129d809d25130aea217"
        }
      ]
    }
  ]
}
