{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.sfsakhawat999",
    "module": "mpvRex-libmpv",
    "version": "0.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mpvRex-libmpv-0.0.9.aar",
          "url": "mpvRex-libmpv-0.0.9.aar",
          "size": 78146230,
          "sha512": "53d5202bb6cea7752498cc5ca207ce4cbddd19966f5504e7241fa944b1e32b8aa5b02db5828ef5c00b93ee3a63cf01270bd2a5b1b680eac7e0ad0daf674a90a9",
          "sha256": "269c7add66abffd67bb656e346df86f29235a939c0831d05d69b606740bf51df",
          "sha1": "87e31956957418581422ea59e8e30b9c7785c82f",
          "md5": "8db752a43a7c2c97c221a054b6a05be4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        }
      ],
      "files": [
        {
          "name": "mpvRex-libmpv-0.0.9.aar",
          "url": "mpvRex-libmpv-0.0.9.aar",
          "size": 78146230,
          "sha512": "53d5202bb6cea7752498cc5ca207ce4cbddd19966f5504e7241fa944b1e32b8aa5b02db5828ef5c00b93ee3a63cf01270bd2a5b1b680eac7e0ad0daf674a90a9",
          "sha256": "269c7add66abffd67bb656e346df86f29235a939c0831d05d69b606740bf51df",
          "sha1": "87e31956957418581422ea59e8e30b9c7785c82f",
          "md5": "8db752a43a7c2c97c221a054b6a05be4"
        }
      ]
    }
  ]
}
