{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.sfsakhawat999",
    "module": "mpvRex-libmpv",
    "version": "v0.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mpvRex-libmpv-v0.0.9.aar",
          "url": "mpvRex-libmpv-v0.0.9.aar",
          "size": 78480082,
          "sha512": "dda9c0eb1be6eb0edab95c12f064f890216879469a5fd22c60dce55a9b68ada14904efdbc8b35d6c740f832703bd3f90cfac8e4948e1143776b978f4300da1f2",
          "sha256": "3723ec60afd3b5c958aa0bb5faaced19f9a6087f5e6e69bbbfd69c4dd2d3c3cc",
          "sha1": "f803169f904df6265c7a73b7ed8944882797632e",
          "md5": "771250dc3bfe0dfdcdc71f2413cfa3c0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        }
      ],
      "files": [
        {
          "name": "mpvRex-libmpv-v0.0.9.aar",
          "url": "mpvRex-libmpv-v0.0.9.aar",
          "size": 78480082,
          "sha512": "dda9c0eb1be6eb0edab95c12f064f890216879469a5fd22c60dce55a9b68ada14904efdbc8b35d6c740f832703bd3f90cfac8e4948e1143776b978f4300da1f2",
          "sha256": "3723ec60afd3b5c958aa0bb5faaced19f9a6087f5e6e69bbbfd69c4dd2d3c3cc",
          "sha1": "f803169f904df6265c7a73b7ed8944882797632e",
          "md5": "771250dc3bfe0dfdcdc71f2413cfa3c0"
        }
      ]
    }
  ]
}
